---
management:
  context-path: /admin
  info:
    git:
      mode: full
spring:
  h2:
    console:
      path: /admin/h2-console
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  profiles:
    include: github
