management:
  info:
    git:
      mode: full
security:
  user: 
    password: password
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
